13-dars/book/urls.py
from django.urls import path
from .views import BookListView, BookDetailView

app_name = 'book'

urlpatterns = [
    path('list/', BookListView.as_view, name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail')
]

13-dars/book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Author(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
class Book(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=12)
    price = models.FloatField()

    def __str__(self):
        return self.title
    
class BookAuthor(models.Model):
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    author_id = models.ForeignKey(Author, on_delete=models.CASCADE)

class BookReview(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

13-dars/book/views.py
from django.shortcuts import render
from django.views import View
from .models import Book

class BookListView(View):
    def get(self, request):
        books = Book.objects.all()
        context = {
            'books' : books
        }
        return render(request, 'book/list.html', context)
    
class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        context = {
            'book' : book
        }
        return render(request, 'book/detail.html', context)

13-dars/book/templates/book/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitob haqida</title>
</head>
<body>
    <h1>Kitob haqida umumiy malumot</h1>
    <h2>Kitob nomi: {{ book.title }}</h2>
    <p>Kitob haqida: {{ book.description }}</p>
    <h2>Kitob muallifi {{ book.author }}</h2>
</body>
</html>

13-dars/book/templates/book/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitoblar ro`yhati</title>
</head>
<body>
    <h1>Kitob lar ro`yhati</h1>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'book:detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>